name: Deploy Full Stack to EC2

on:
  push:
    branches:
      - main # Double-check if your branch is 'main' or 'master'

jobs:
  deploy-full-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.8'

      - name: Build Frontend
        run: |
          cd milkify-next
          npm install
          npm run build
          cd ..

      - name: Compress Full Stack
        # GitHub starts with a fresh copy of your code, so there are no heavy node_modules in the Backend folder yet to slow down the zip!
        run: |
          tar -czf deploy.tar.gz milkify-next/.next milkify-next/public milkify-next/package.json milkify-next/package-lock.json milkify-next/next.config.* Backend/
      - name: Send files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "deploy.tar.gz"
          target: "/home/ubuntu/My-Dairy"

      - name: Unzip and Restart Both Services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/My-Dairy
            tar -xzf deploy.tar.gz
            
            # 1. Update Frontend
            cd milkify-next
            npm install --omit=dev
            pm2 restart my-dairy-frontend
            
            # 2. Update Backend
            cd ../Backend
            npm install
            pm2 restart my-dairy