export const FARMER_USER_REQUEST = "FARMER_USER_REQUEST";
export const FARMER_USER_SUCCESS = "FARMER_USER_SUCCESS";
export const FARMER_USER_FAILURE = "FARMER_USER_FAILURE";


export const GET_FARMER_REQUEST = "GET_FARMER_REQUEST";
export const GET_FARMER_SUCCESS = "GET_FARMER_SUCCESS";
export const GET_FARMER_FAILURE = "GET_FARMER_FAILURE";

