//MASTER
//POST
export const POST_REQUEST="POST_REQUEST";
export const POST_SUCCESS="POST_SUCCESS";
export const POST_FAILURE="POST_FAILURE";

//GET
export const GET_REQUEST="GET_REQUEST";
export const GET_SUCCESS="GET_SUCCESS";
export const GET_FAILURE="GET_FAILURE";

//PATCH
export const PATCH_REQUEST="PATCH_REQUEST";
export const PATCH_SUCCESS="PATCH_SUCCESS";
export const PATCH_FAILURE="PATCH_FAILURE";

//DELETE
export const DELETE_REQUEST="DELETE_REQUEST";
export const DELETE_SUCCESS="DELETE_SUCCESS";
export const DELETE_FAILURE="DELETE_FAILURE";


//Login
export const POST_LOGIN_REQUEST="POST_LOGIN_REQUEST";
export const POST_LOGIN_SUCCESS="POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILURE="POST_LOGIN_FAILURE";

//REGISTER
export const POST_REGISTER_REQUEST="POST_REGISTER_REQUEST";
export const POST_REGISTER_SUCCESS="POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAILURE="POST_REGISTER_FAILURE";
// POST 
export const POST_USER_REQUEST="POST_USER_REQUEST";
export const POST_USER_SUCCESS="POST_USER_SUCCESS";
export const POST_USER_FAILURE="POST_USER_FAILURE";
//GET
export const GET_USER_REQUEST="GET_USER_REQUEST";
export const GET_USER_SUCCESS="GET_USER_SUCCESS";
export const GET_USER_FAILURE="GET_USER_FAILURE";

//edit product
export const EDIT_PRODUCT_REQUEST="EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS="EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE="EDIT_PRODUCT_FAILURE";

//delete 
//edit product
export const DELETE_USER_REQUEST="DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE="DELETE_USER_FAILURE";