export const POST_PRODUCT_REQUEST="POST_PRODUCT_REQUEST";
export const POST_PRODUCT_SUCCESS="POST_PRODUCT_SUCCESS";
export const POST_PRODUCT_FAILURE="POST_PRODUCT_FAILURE";

//GET
export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE="GET_PRODUCT_FAILURE";

//edit product
export const EDIT_PRODUCT_REQUEST="EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS="EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE="EDIT_PRODUCT_FAILURE";

//delete 
//edit product
export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE="DELETE_PRODUCT_FAILURE";