export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILURE = "USER_SIGNIN_FAILURE";

export const USER_LOGOUT_REQUEST="USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS="USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE="USER_LOGOUT_FAILURE";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";

export const USER_MESSAGE_REQUEST = "USER_MESSAGE_REQUEST";
export const USER_MESSAGE_SUCCESS = "USER_MESSAGE_SUCCESS";
export const USER_MESSAGE_FAILURE = "USER_MESSAGE_FAILURE";

export const RESET_REQUEST ="RESET_REQUEST";