export const ADD_MILK_REQUEST="ADD_MILK_REQUEST";
export const ADD_MILK_SUCCESS="ADD_MILK_SUCCESS";
export const ADD_MILK_FAILURE="ADD_MILK_FAILURE";

export const GET_MILK_REQUEST="GET_MILK_REQUEST";
export const GET_MILK_SUCCESS="GET_MILK_SUCCESS";
export const GET_MILK_FAILURE="GET_MILK_FAILURE";